const AiCodegenMixin = {
    bindCodeGen() {
        document.getElementById('framework-tabs').addEventListener('click', (e) => {
            const tab = e.target.closest('.tab-item');
            if (!tab) return;
            document.querySelectorAll('#framework-tabs .tab-item').forEach(t => t.classList.remove('active'));
            tab.classList.add('active');
            this.currentFramework = tab.dataset.fw;
        });

        document.getElementById('generate-ai-code-btn').addEventListener('click', () => {
            const prompt = document.getElementById('ai-code-prompt').value.trim();
            if(!prompt) return Toast.show('Please enter a description first', 'error');
            this.generateAICode(prompt);
        });

        document.getElementById('copy-code-btn').addEventListener('click', () => {
            const code = this.editor ? this.editor.getValue() : '';
            if(!code) return Toast.show('No code to copy', 'error');
            Helpers.copyToClipboard(code);
            Toast.show('Code copied to clipboard!', 'success');
        });

        document.getElementById('save-workspace-btn').addEventListener('click', () => {
            const code = this.editor ? this.editor.getValue() : '';
            if(!code) return Toast.show('No code to save', 'error');
            const fw = this.currentFramework;
            WorkspacePage.saveSnippet(`AI Generated ${fw.toUpperCase()}`, code, fw);
            Toast.show('Saved to My Workspace!', 'success');
        });

        document.getElementById('run-container-btn').addEventListener('click', async () => {
            const outputDiv = document.getElementById('ai-code-output');
            const code = this.editor ? this.editor.getValue() : '';
            if(!code.trim() || code.includes('// Code generation failed')) return Toast.show('No valid code to run', 'warning');

            const fw = this.currentFramework;
            let project = {
                title: 'Vertex AI Output',
                description: 'Generated by Vertex Developer Toolkit',
                template: 'javascript',
                files: { 'index.js': code }
            };

            if (fw === 'react') {
                project.template = 'create-react-app';
                project.files = {
                    'src/App.js': `import React from 'react';\nimport './style.css';\n\n${code}`,
                    'src/index.js': 'import React from "react";\nimport { createRoot } from "react-dom/client";\nimport App from "./App";\nconst root = createRoot(document.getElementById("root"));\nroot.render(<App />);',
                    'public/index.html': '<div id="root"></div>',
                    'src/style.css': 'body { font-family: sans-serif; padding: 20px; }'
                };
            } else if (fw === 'vue') {
                project.template = 'node';
                project.files = { 
                    'package.json': '{"name":"vue-preview","scripts":{"start":"vite"},"dependencies":{"vue":"^3.2.0"},"devDependencies":{"vite":"^4.0.0","@vitejs/plugin-vue":"^4.0.0"}}',
                    'index.html': '<div id="app"></div><script type="module" src="/main.js"><\/script>',
                    'main.js': 'import { createApp } from "vue";\nimport App from "./App.vue";\ncreateApp(App).mount("#app");',
                    'App.vue': code,
                    'vite.config.js': 'import { defineConfig } from "vite";\nimport vue from "@vitejs/plugin-vue";\nexport default defineConfig({plugins:[vue()]});'
                };
            } else if (fw === 'html') {
                project.template = 'html';
                project.files = { 'index.html': code };
            } else if (fw === 'python') {
                return Toast.show('WebContainers Python runtime coming soon. Try React/Vue/HTML.', 'info');
            }

            if (!window.StackBlitzSDK) {
                Toast.show('Loading WebContainer...', 'info', 2000);
                await Helpers.loadScript('https://unpkg.com/@stackblitz/sdk/bundles/sdk.umd.js');
            }

            let embedWrap = document.getElementById('stackblitz-embed-wrap');
            if (embedWrap) embedWrap.remove();

            embedWrap = document.createElement('div');
            embedWrap.id = 'stackblitz-embed-wrap';
            embedWrap.style.cssText = 'margin-top:20px;';
            embedWrap.innerHTML = `
                <div class="glass-card-static" style="padding:0; overflow:hidden;">
                    <div style="display:flex;justify-content:space-between;align-items:center;padding:12px 16px;border-bottom:1px solid var(--border);">
                        <div style="display:flex;align-items:center;gap:8px;">
                            <span style="width:8px;height:8px;border-radius:50%;background:#22c55e;display:inline-block;"></span>
                            <span style="font-size:0.88rem;font-weight:600;color:var(--text);">Live Workspace</span>
                        </div>
                        <button class="btn btn-ghost btn-xs" id="close-embed-btn"><i class="fa-solid fa-xmark"></i></button>
                    </div>
                    <div id="stackblitz-embed" style="height:450px;"></div>
                </div>`;
            document.getElementById('generator-output-area').appendChild(embedWrap);
            document.getElementById('close-embed-btn').addEventListener('click', () => { embedWrap.style.display = 'none'; });
            embedWrap.style.display = 'block';

            Toast.show('Booting Live Server...', 'success');
            window.StackBlitzSDK.embedProject(
                document.getElementById('stackblitz-embed'),
                project,
                { openFile: Object.keys(project.files).find(f => f.includes('App') || f.includes('index')), height: 450, forceEmbedLayout: true }
            );
        });
    },

    async generateAICode(prompt) {
        document.getElementById('generator-output-area').style.display = 'none';
        document.getElementById('loading-overlay').style.display = 'block';

        const systemPrompt = `You are an expert coder. Write ONLY the code for a ${prompt} component using ${this.currentFramework}. Do NOT include markdown blocks like \`\`\`html or \`\`\`javascript, and do NOT include any explanations. Output pure, valid code.`;
        
        try {
            let code = '';
            try {
                const controller = new AbortController();
                const timeout = setTimeout(() => controller.abort(), 60000);
                
                const res = await fetch('https://text.pollinations.ai/', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        messages: [
                            { role: 'system', content: systemPrompt },
                            { role: 'user', content: prompt }
                        ],
                        model: 'openai',
                        seed: Math.floor(Math.random() * 100000)
                    }),
                    signal: controller.signal
                });
                clearTimeout(timeout);
                if (!res.ok) throw new Error('API failed');
                
                code = await res.text();
                if (typeof AskAiPage !== 'undefined' && AskAiPage.cleanAiResponse) {
                    code = AskAiPage.cleanAiResponse(code);
                }
            } catch(postErr) {
                code = '// Code generation failed or API is busy. Please try again.';
            }
            
            code = code.replace(/^```[a-zA-Z]*\n?/gm, '').replace(/\n?```$/gm, '').trim();

            document.getElementById('loading-overlay').style.display = 'none';
            document.getElementById('generator-output-area').style.display = 'block';
            document.getElementById('output-fw-tag').textContent = this.currentFramework.toUpperCase();
            
            if (this.editor) {
                this.editor.setValue('');
                let lang = this.currentFramework;
                if(lang === 'vue' || lang === 'react') lang = 'html';
                window.monaco?.editor.setModelLanguage(this.editor.getModel(), lang);
                this.editor.setValue(code);
            }
        } catch(e) {
            document.getElementById('loading-overlay').style.display = 'none';
            Toast.show('Failed to generate code. Please try again.', 'error');
        }
    }
};
