const AiCodegenMixin = {
    bindCodeGen() {
        console.log('[Code Gen] Starting code gen binding...');
        
        const frameworkTabs = document.getElementById('framework-tabs');
        const generateBtn = document.getElementById('generate-ai-code-btn');
        const copyBtn = document.getElementById('copy-code-btn');
        const saveBtn = document.getElementById('save-workspace-btn');
        const runBtn = document.getElementById('run-container-btn');
        const codePrompt = document.getElementById('ai-code-prompt');
        
        console.log('[Code Gen] Elements found:', {
            frameworkTabs: !!frameworkTabs,
            generateBtn: !!generateBtn,
            copyBtn: !!copyBtn,
            saveBtn: !!saveBtn,
            runBtn: !!runBtn,
            codePrompt: !!codePrompt
        });
        
        if (!frameworkTabs || !generateBtn || !copyBtn || !saveBtn || !runBtn || !codePrompt) {
            console.warn('[Code Gen] Missing code gen elements - skipping binding');
            return;
        }
        
        // Framework tabs
        frameworkTabs.addEventListener('click', (e) => {
            const tab = e.target.closest('.tab-item');
            if (!tab) return;
            document.querySelectorAll('#framework-tabs .tab-item').forEach(t => t.classList.remove('active'));
            tab.classList.add('active');
            this.currentFramework = tab.dataset.fw;
            console.log('[Code Gen] Selected framework:', this.currentFramework);
        });

        // Generate button
        generateBtn.addEventListener('click', () => {
            console.log('[Code Gen] Generate button clicked');
            const prompt = codePrompt.value.trim();
            console.log('[Code Gen] Generate prompt:', prompt.substring(0, 50));
            if(!prompt) {
                Toast.show('Please enter a description first', 'error');
                return;
            }
            console.log('[Code Gen] Calling generateAICode');
            this.generateAICode(prompt);
        });

        // Copy button
        copyBtn.addEventListener('click', () => {
            console.log('[Code Gen] Copy button clicked');
            const code = this.editor ? this.editor.getValue() : '';
            if(!code) {
                Toast.show('No code to copy', 'error');
                return;
            }
            Helpers.copyToClipboard(code);
            Toast.show('Code copied to clipboard!', 'success');
        });

        // Save button
        saveBtn.addEventListener('click', () => {
            console.log('[Code Gen] Save button clicked');
            const code = this.editor ? this.editor.getValue() : '';
            if(!code) {
                Toast.show('No code to save', 'error');
                return;
            }
            const fw = this.currentFramework;
            WorkspacePage.saveSnippet(`AI Generated ${fw.toUpperCase()}`, code, fw);
            Toast.show('Saved to My Workspace!', 'success');
        });

        // Run button
        runBtn.addEventListener('click', async () => {
            console.log('[Code Gen] Run button clicked');
            const outputDiv = document.getElementById('ai-code-output');
            const code = this.editor ? this.editor.getValue() : '';
            if(!code.trim() || code.includes('// Code generation failed')) {
                Toast.show('No valid code to run', 'warning');
                return;
            }

            const fw = this.currentFramework;
            let project = {
                title: 'Vertex AI Output',
                description: 'Generated by Vertex Developer Toolkit',
                template: 'javascript',
                files: { 'index.js': code }
            };

            if (fw === 'html') {
                const outputDiv = document.getElementById('ai-code-output');
                let embedWrap = document.getElementById('stackblitz-embed-wrap');
                if (embedWrap) embedWrap.remove();
                
                embedWrap = document.createElement('div');
                embedWrap.id = 'stackblitz-embed-wrap';
                embedWrap.style.cssText = 'margin-top:20px;';
                embedWrap.innerHTML = `
                    <div class="glass-card-static" style="padding:0; overflow:hidden;">
                        <div style="display:flex;justify-content:space-between;align-items:center;padding:12px 16px;border-bottom:1px solid var(--border);">
                            <div style="display:flex;align-items:center;gap:8px;">
                                <span style="width:8px;height:8px;border-radius:50%;background:#22c55e;display:inline-block;"></span>
                                <span style="font-size:0.88rem;font-weight:600;color:var(--text);">Live Preview</span>
                            </div>
                            <button class="btn btn-ghost btn-xs" id="close-embed-btn"><i class="fa-solid fa-xmark"></i></button>
                        </div>
                        <iframe id="html-preview-iframe" style="width:100%;height:450px;border:none;background:white;" sandbox="allow-scripts allow-forms allow-same-origin"></iframe>
                    </div>`;
                document.getElementById('generator-output-area').appendChild(embedWrap);
                document.getElementById('close-embed-btn').addEventListener('click', () => { embedWrap.style.display = 'none'; });
                
                const iframe = document.getElementById('html-preview-iframe');
                if (iframe) iframe.srcDoc = code;
                Toast.show('HTML preview loaded!', 'success');
                return;
            }

            if (fw === 'react') {
                project.template = 'create-react-app';
                project.files = {
                    'src/App.js': `import React from 'react';\nimport './style.css';\n\n${code}`,
                    'src/index.js': 'import React from "react";\nimport { createRoot } from "react-dom/client";\nimport App from "./App";\nconst root = createRoot(document.getElementById("root"));\nroot.render(<App />);',
                    'public/index.html': '<div id="root"></div>',
                    'src/style.css': 'body { font-family: sans-serif; padding: 20px; }'
                };
            } else if (fw === 'vue') {
                project.template = 'node';
                project.files = { 
                    'package.json': '{"name":"vue-preview","scripts":{"start":"vite"},"dependencies":{"vue":"^3.2.0"},"devDependencies":{"vite":"^4.0.0","@vitejs/plugin-vue":"^4.0.0"}}',
                    'index.html': '<div id="app"></div><script type="module" src="/main.js"><\/script>',
                    'main.js': 'import { createApp } from "vue";\nimport App from "./App.vue";\ncreateApp(App).mount("#app");',
                    'App.vue': code,
                    'vite.config.js': 'import { defineConfig } from "vite";\nimport vue from "@vitejs/plugin-vue";\nexport default defineConfig({plugins:[vue()]});'
                };
            } else if (fw === 'python') {
                return Toast.show('WebContainers Python runtime coming soon. Try React/Vue/HTML.', 'info');
            }

            if (!window.StackBlitzSDK) {
                Toast.show('Loading development environment...', 'info', 3000);
                try {
                    await Helpers.loadScript('https://unpkg.com/@stackblitz/sdk/bundles/sdk.umd.js');
                    // Wait for SDK to be available (up to 3 seconds)
                    let retries = 0;
                    while (!window.StackBlitzSDK && retries < 30) {
                        await new Promise(r => setTimeout(r, 100));
                        retries++;
                    }
                } catch (e) {
                    console.error('[StackBlitz Load Error]:', e);
                }
                
                if (!window.StackBlitzSDK) {
                    Toast.show('Development environment unavailable. Showing code instead.', 'warning');
                    document.getElementById('generator-output-area').scrollIntoView({ behavior: 'smooth' });
                    return;
                }
            }

            let embedWrap = document.getElementById('stackblitz-embed-wrap');
            if (embedWrap) embedWrap.remove();

            embedWrap = document.createElement('div');
            embedWrap.id = 'stackblitz-embed-wrap';
            embedWrap.style.cssText = 'margin-top:20px;';
            embedWrap.innerHTML = `
                <div class="glass-card-static" style="padding:0; overflow:hidden;">
                    <div style="display:flex;justify-content:space-between;align-items:center;padding:12px 16px;border-bottom:1px solid var(--border);">
                        <div style="display:flex;align-items:center;gap:8px;">
                            <span style="width:8px;height:8px;border-radius:50%;background:#22c55e;display:inline-block;"></span>
                            <span style="font-size:0.88rem;font-weight:600;color:var(--text);">Live Workspace</span>
                        </div>
                        <button class="btn btn-ghost btn-xs" id="close-embed-btn"><i class="fa-solid fa-xmark"></i></button>
                    </div>
                    <div id="stackblitz-embed" style="height:450px;"></div>
                </div>`;
            document.getElementById('generator-output-area').appendChild(embedWrap);
            document.getElementById('close-embed-btn').addEventListener('click', () => { embedWrap.style.display = 'none'; });
            embedWrap.style.display = 'block';

            Toast.show('Booting Live Server...', 'success');
            
            if (!window.StackBlitzSDK) {
                return Toast.show('WebContainer SDK not available', 'error');
            }
            
            window.StackBlitzSDK.embedProject(
                document.getElementById('stackblitz-embed'),
                project,
                { openFile: Object.keys(project.files).find(f => f.includes('App') || f.includes('index')), height: 450, forceEmbedLayout: true }
            );
        });

        console.log('[Code Gen] Code gen binding complete - all event listeners attached');
    },

    async generateAICode(prompt) {
        document.getElementById('generator-output-area').style.display = 'none';
        document.getElementById('loading-overlay').style.display = 'block';

        const systemPrompt = `You must generate valid ${this.currentFramework} code. Do not include: markdown, code blocks, backticks, explanations, or comments. Output ONLY pure executable code.`;
        
        try {
            let code = '';
            try {
                const res = await API.callGroqChat([
                    { role: 'system', content: systemPrompt },
                    { role: 'user', content: `Generate ${this.currentFramework} code for: ${prompt}` }
                ], 'llama-3.1-8b-instant', 0.7);
                
                code = res.choices?.[0]?.message?.content || '';
                console.log('[CodeGen Raw Response]:', code.substring(0, 200));
                
                // Aggressive cleaning - remove markdown fences safely
                code = code
                    .replace(/^```[a-zA-Z0-9\-]*\n?/gm, '') // Remove starting fence + language tag
                    .replace(/\n?```$/gm, '')                // Remove ending fence
                    .replace(/`{1,3}/g, '')                  // Remove any stray backticks
                    .trim();
                
                console.log('[CodeGen Cleaned]:', code.substring(0, 200));
                
                if (!code || code.length < 10) {
                    code = '<!-- Failed to generate valid code. Try a more specific prompt -->';
                }
            } catch(postErr) {
                console.error('[Code Generator Error]', postErr.message);
                code = `<!-- Error: ${postErr.message} -->\n<!-- Please check console and ensure Groq Proxy is running -->`;
            }

            document.getElementById('loading-overlay').style.display = 'none';
            document.getElementById('generator-output-area').style.display = 'block';
            document.getElementById('output-fw-tag').textContent = this.currentFramework.toUpperCase();
            
            if (this.editor) {
                this.editor.setValue('');
                let lang = this.currentFramework;
                if(lang === 'vue' || lang === 'react') lang = 'html';
                window.monaco?.editor.setModelLanguage(this.editor.getModel(), lang);
                this.editor.setValue(code);
                console.log('[CodeGen Editor Updated with:', code.length, 'chars]');
            } else {
                console.error('[CodeGen] Editor not initialized');
            }
        } catch(e) {
            console.error('[CodeGen Exception]', e);
            document.getElementById('loading-overlay').style.display = 'none';
            Toast.show('Failed to generate code. Please try again.', 'error');
        }
    }
};
